spring:
  datasource:
    drive-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wizard?useUnicode=true&characterEncoding=utf-8
    username: root
    password: wizard
  aop:
    proxy-target-class: true