# spring default config
spring.redis:
  host: localhost
  port: 6379
  timeout: 5000
  lettuce.pool:
    # max connection number in connection poll, default number is 8
    max-active: 20
    # max wait time, default -1, this means there is no restrict. Unit: ms
    max-wait: -1
    # max idle connection number, default is 8
    max-idle: 8
    # min idle connection number, default is 0
    min-idle: 0
#  cluster.nodes:
#    - 10.100.113.38:7000
#    - 10.100.113.38:7001
#    - 10.100.113.38:7002
#    - 10.100.113.38:7003
#    - 10.100.113.38:7004
#    - 10.100.113.38:7005
#    - 10.100.113.38:7006
#    - 10.100.113.38:7007

#config more clusters
spring.redis-wizard:
  point:
    - localhost:6379
  lettuce.pool:
    max-active: 10
    max-wait: -1
    max-idle: 10
    min-idle: 5
