server:
  port: 9090
logging:
  level:
    com:
      dev: debug #com.dev为包路径

eureka:
  client:
    register-with-eureka: true #注册到Eureka的注册中心
    fetch-registry: true #获取注册实例列表
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:  #全局配置
        loggerLevel: FULL
        connectTimeout: 1000 # 连接时间
        readTimeout: 1000 # 读取超时时间 两者同时配置才可以生效
        #retryer: com.dev.wizard.config.RetryerConfig
  okhttp:
    enabled: true
  httpclient:
    enable: true

