server:
  port: 80
spring:
  main:
    allow-circular-references: true

# spring default config
spring.redis:
  host: <your-ipv4>
  password: redispw
  port: 49153
  timeout: 5000
  lettuce.pool:
    # max connection number in connection poll, default number is 8
    max-active: 20
    # max wait time, default -1, this means there is no restrict. Unit: ms
    max-wait: -1
    # max idle connection number, default is 8
    max-idle: 8
    # min idle connection number, default is 0
    min-idle: 0